## Colors configuration
[colors.primary]
background = "#000000"
foreground = "#c3c3c3"

[colors.normal]
black   = "#000000"
red     = "#2B2B2B"
green   = "#333333"
yellow  = "#3B3B3B"
blue    = "#464646"
magenta = "#565656"
cyan    = "#6D6D6D"
white   = "#c3c3c3"

[colors.bright]
black   = "#888888"
red     = "#2B2B2B"
green   = "#333333"
yellow  = "#3B3B3B"
blue    = "#464646"
magenta = "#565656"
cyan    = "#6D6D6D"
white   = "#c3c3c3"
