## Colors configuration
[colors.primary]
background = "#12121b"
foreground = "#c3c3c6"

[colors.normal]
black   = "#12121b"
red     = "#3F6683"
green   = "#565D81"
yellow  = "#675B82"
blue    = "#4B6584"
magenta = "#6E6188"
cyan    = "#A46786"
white   = "#c3c3c6"

[colors.bright]
black   = "#5c5c71"
red     = "#3F6683"
green   = "#565D81"
yellow  = "#675B82"
blue    = "#4B6584"
magenta = "#6E6188"
cyan    = "#A46786"
white   = "#c3c3c6"
