# Shell variables
# Generated by 'wal'
wallpaper='/home/sosiska/Изображения/wallpapers/windows-11-dark-mode-abstract-background-black-background-3840x2400-8710.jpg'

# Special
background='#000000'
foreground='#c3c3c3'
cursor='#c3c3c3'

# Colors
color0='#000000'
color1='#2B2B2B'
color2='#333333'
color3='#3B3B3B'
color4='#464646'
color5='#565656'
color6='#6D6D6D'
color7='#c3c3c3'
color8='#888888'
color9='#2B2B2B'
color10='#333333'
color11='#3B3B3B'
color12='#464646'
color13='#565656'
color14='#6D6D6D'
color15='#c3c3c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
