# Shell variables
# Generated by 'wal'
wallpaper="/home/soaska/wallpapers/wallpaper.jpg"

# Special
background='#12121b'
foreground='#c3c3c6'
cursor='#c3c3c6'

# Colors
color0='#12121b'
color1='#3F6683'
color2='#565D81'
color3='#675B82'
color4='#4B6584'
color5='#6E6188'
color6='#A46786'
color7='#c3c3c6'
color8='#5c5c71'
color9='#3F6683'
color10='#565D81'
color11='#675B82'
color12='#4B6584'
color13='#6E6188'
color14='#A46786'
color15='#c3c3c6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
