#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Set Wallpaper in Hyprland

WALLPAPER='/home/sosiska/Изображения/wallpapers/arch-black-4k.png'

swaybg --output '*' --mode fill --image "$WALLPAPER"
