#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Set Wallpaper in Hyprland

WALLPAPER='/home/sosiska/Изображения/wallpapers/windows-11-dark-mode-abstract-background-black-background-3840x2400-8710.jpg'

swaybg --output '*' --mode fill --image "$WALLPAPER"
